import type { NextPage } from 'next'
import React from 'react';
import Head from 'next/head'
import { useRouter } from 'next/router';

const Product: NextPage = () => {

  const router = useRouter()

  return (
    <div className="px-4 px-md-0">
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1 className='py-4 my-2'>product {router.query?.id}</h1>

    </div>
  )
}

export default Product
