import type { NextPage } from 'next'
import React from 'react';
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import api from '../services/api';


import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Carousel from 'react-bootstrap/Carousel';
import Card from 'react-bootstrap/Card';
import Button from 'react-bootstrap/Button';
import Link from 'next/link';


const Home: NextPage = () => {
  const [data, setData] = React.useState<any[]>([])
  React.useEffect(() => {
    (async () => {
      try {
        const { data } = await api.get("/fruit/all")
        setData(data)
      } catch(err) {
        console.log(JSON.stringify(err))
      }
    })()
  }, [])

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Hortifruti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
      {data?.map((item) => (
        <p>{item?.name}</p>
      ))}
    </div>
      

  <body>

  <Container>
      <Row>
        
        <Col sm={9} className="mt-5"> <Carousel>
      <Carousel.Item>
        <img
          className="d-block w-100 opacity-75"
          src="https://live.staticflickr.com/8792/28207597872_4f3b4d4005_b.jpg"
          alt="First slide"
        />
        <Carousel.Caption>
          <h3>Frutas</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
          <Link passHref shallow href={`/categories/${'Frutas'}`}>
            <a className="btn btn-success mb-4">Confira agora!</a>
          </Link>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100 opacity-75"
          src="https://www.sindcontsp.org.br/wp-content/uploads/2022/05/20140530por-ramiro-furquim-_oaf1186.jpg"
          alt="Second slide"
        />

        <Carousel.Caption >

          <h3>Legumes</h3>

          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

          <Link passHref shallow href={`/categories/${'Legumes'}`}>
            <a className="btn btn-success mb-4">Confira agora!</a>
          </Link>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100 opacity-75"
          src="https://imagens.mfrural.com.br/mfrural-produtos-us/337934-339321-1852220-verduras-nobre.jpg"
          alt="Third slide"
        />

        <Carousel.Caption>
          <h3>Verduras</h3>
          <p>
            Praesent commodo cursus magna, vel scelerisque nisl consectetur.
          </p>
          <Link passHref shallow href={`/categories/${'Verduras'}`}>
            <a className="btn btn-success mb-4">Confira agora!</a>
          </Link>
        </Carousel.Caption>
      </Carousel.Item>

      
      
    </Carousel>
    </Col>
        <Col sm={3} className="mt-5">
        <div className="card rounded-0 border-0">
        <img src="https://www.designi.com.br/images/preview/10003522.jpg" className="card-img-top rounded-0" alt="..."/>

        </div>
        <div className="card mt-4 rounded-0 pt-2 border-0">
        <img src="https://www.designi.com.br/images/preview/10003592.jpg" className="card-img-top rounded-0" alt="..."/>

        </div>
      </Col>
      
        <div className="card border-0 mt-3">
        <div className="card-body d-flex justify-content-center">
      <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
    </Row>
  </Container>

<footer>
  <div className="bg-success  text-white">
    <Nav className="justify-content-center mt-4" >
        <p className='mt-3'>NOVO JEITO DE FAZER FEIRA</p>
      </Nav>
  </div>
</footer>


</body>

    </div>
  )
}



export default Home
