import type { NextPage } from 'next'
import React from 'react';
import Head from 'next/head'
import BagContext from '../contexts/bag';
import styles from '../styles/Home.module.css'
import api from '../services/api';

import Stack from 'react-bootstrap/Stack';
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Carousel from 'react-bootstrap/Carousel';
import Card from 'react-bootstrap/Card';
import Button from 'react-bootstrap/Button';



const Home: NextPage = () => {
  const [data, setData] = React.useState<any[]>([])
  const { bag, saveInBag, removeInBag, updateInBag } = React.useContext(BagContext)

  React.useEffect(() => {
    (async () => {
      try {
        const { data } = await api.get("/fruit/all")
        setData(data)
      } catch(err) {
        console.log(JSON.stringify(err))
      }
    })()
  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Hortifrut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div>
      {data?.map((item) => (
        <p>{item?.name}</p>
      ))}
    </div>
      




  <body>

  <header>
  <Navbar bg="dark" variant="dark">
    <Container  fluid className="p-3 ">
      <Navbar.Brand href="#home">Navbar</Navbar.Brand>
        <Nav>
          <Stack direction="horizontal" gap={3}>
            <Nav.Link href="#home">Home</Nav.Link>
            <Nav.Link href="#features">Produtos</Nav.Link>
            <Nav.Link href="#pricing">Carrinho</Nav.Link>
          </Stack>
        </Nav>
      </Container>
    </Navbar>
  </header>

  <Container className='col-md-6'>
    <Row fluid className="p-4">
    <Stack direction="horizontal" gap={3}>
      <div>COMEÇAR PEDIDO  </div>
      <div><Button variant="danger">ENTREGA</Button>{' '}</div>
      <div>ou</div>
      <div><Button variant="danger">RETIRAR NA LOJA</Button>{' '}</div>
    </Stack>
    </Row>
  </Container>

  <Container>
      <Row>
        <Col sm={8}> <Carousel>
      <Carousel.Item>
        <img
          className="d-block w-100 "
          src="https://live.staticflickr.com/8792/28207597872_4f3b4d4005_b.jpg"
          alt="First slide"
        />
        <Carousel.Caption>
          <h3>Frutas</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="https://www.sindcontsp.org.br/wp-content/uploads/2022/05/20140530por-ramiro-furquim-_oaf1186.jpg"
          alt="Second slide"
        />

        <Carousel.Caption>
          <h3>Legumes</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="https://imagens.mfrural.com.br/mfrural-produtos-us/337934-339321-1852220-verduras-nobre.jpg"
          alt="Third slide"
        />

        <Carousel.Caption>
          <h3>Verduras</h3>
          <p>
            Praesent commodo cursus magna, vel scelerisque nisl consectetur.
          </p>
        </Carousel.Caption>
      </Carousel.Item>

      
      
    </Carousel></Col>
        <Col sm={4}>
          <Card style={{ width: '14rem' }}>
            <Card.Img src="https://media-exp1.licdn.com/dms/image/C4D22AQGh6PT-3-ibHw/feedshare-shrink_800/0/1657724236759?e=1662595200&v=beta&t=k6EAZQCCl6GEYdgpM44kRQ4B7w12ZaFtKnKDv_ikmWM"/>
          </Card> 

          <Card className='mt-4' style={{ width: '14rem' }}>
            <Card.Img src="https://st.depositphotos.com/1755345/54065/i/600/depositphotos_540655824-stock-photo-hortifruti-banner-or-poster-for.jpg"/>
          </Card>
        </Col>
      </Row>
    </Container>

<footer>
  <Nav className="justify-content-center mt-4" >
      <Nav.Item >
        <Nav.Link href="/home">Politica de Privacidade</Nav.Link>
      </Nav.Item>
      <Nav.Item>
        <Nav.Link eventKey="link-1">Fale Conosco</Nav.Link>
      </Nav.Item>
      <Nav.Item>
        <Nav.Link eventKey="link-2">Termos de Uso</Nav.Link>
      </Nav.Item>
    </Nav>
</footer>


</body>

      {/* <h1>{bag.length}</h1>


        <button className='btn btn-primary' onClick={() => saveInBag({ _id: Math.random().toString(), price: 12, name: 'remove' })}>add product</button>

        <h1>bag</h1>

        {bag.map(item => (
          <div key={item._id} className="div">
            <button  className='btn btn-primary' onClick={() => removeInBag(item._id)} >{item.name}</button>
            <input className='form-control' 
              defaultValue={item.price.toString()} 
              onChange={e => updateInBag(item._id, {
                ...item,
                price: Number(e.target.value),
              })}
            />
          </div>
        ))} */}
    </div>
  )
}



export default Home
